### ISSUE TITLE
Photos Sync

### ISSUE THREAD

**Issue by GaborElAyoubi** [Infomaniak/ios-kDrive#1062]
Actual behavior:

Sync iphone photos makes from Phone > kDrive. 
When i delete a photo in Photos, it gets not sync with kDrive.

Should:

The older(already sync) should also be checked again.
The photos in kDrive should be same as photos on iPhone.

**Comment by PhilippeWeidmann** [comment]
Hi, thank you for your feedback. 
Sadly this feature goes out of scope for this app. Currently kDrive offers a way to backup your pictures but it's not meant to be a perfect mirror of your photo library.

We hope that some day we will be able to develop a perfect replacement for you photo app that will sync pictures and albums.
