### ISSUE TITLE
Configurable „Home“ button

### ISSUE THREAD

**Issue by MajorTomDE** [Infomaniak/ios-kDrive#1312]
Hello,

currently the „Home“ button within the kDrive iOS apps shows the last changes.

I am not interested in this and would rather have the root folder of "My files".

So my suggestion is a function to configure the „Home“ button to set the e.g.

- My Files
- Favorites 
- Last Changed
- Offline
- …

The big adventure is a faster access to the really need folder.

**Comment by dixy** [comment]
I am also interested, specially since the last release removes the favorites button from the navigation bar (it adds a step to open favorites...).

**Comment by PhilippeWeidmann** [comment]
Hello, this kind of feature requests are handled by product here:
(fr) https://feedback.userreport.com/98c496bd-384f-4805-8a0b-d9f73f35cf96
(en) https://feedback.userreport.com/8095da03-4efe-469e-9aef-c7745ef85f6a
(de) https://feedback.userreport.com/b9a9acec-ada6-471f-a473-c91f22be2acc
