### ISSUE TITLE
Scan document can overwrite existing file

### ISSUE THREAD

**Issue by marcheimendinger** [Infomaniak/ios-kDrive#158]
**Description**
Uploading a scanned document can lead to overwriting an existing one with the same name.

**Steps to reproduce**
1. Scan a document named `test.pdf` in a directory.
2. Scan another document also named `test.pdf ` in the same directory.
3. The first document is overwritten by the new one.

**Expected behavior**
In this use case, the app should raise a popup error or upload it with a slightly different name (`test-1.pdf` in my example).

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - iOS version: 14.5.1
 - App version: 4.0.5 (11)

**Comment by flowbe** [comment]
This is an expected behavior: we create a new version of the file when it already exists. Maybe we should handle it differently but this is useful in some cases. Adding a number to the file name also makes sense (it's actually the behavior in the File Provider), so we have to think about it.

**Comment by alxschilling** [comment]
autoupload -> replace
Manual upload > duplicate if needed

**Comment by flowbe** [comment]
https://github.com/Infomaniak/android-kDrive/pull/292/files
