### ISSUE TITLE
Graphic glitch when selecting an empty folder

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/ios-kDrive#181]
Hello,

Glitch on the home of the app and when you select an empty folder.

You have a black bar that appears in the top right corner, see video for reference.

iOS : 15b2 (seen on 14.6 too)
kDrive : 4.0.6 (1)

https://www.swisstransfer.com/d/ca991c66-250b-42c0-9f0d-6f1dd3d8bf74

Have a nice day !

**Comment by PhilippeWeidmann** [comment]
Resolved with new home
