### ISSUE TITLE
Sauvegarde des photos (se désactive automatiquement)

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/ios-kDrive#184]
Je configure la sauvegarde auto des photos (sans les vidéos, à partir de maintenant, avec classement dans dossiers, avec suppression des photos transférées). Rien ne se sauvegarde quand je prends de nouvelles oeuvres d'art et quand je retourne dans les paramètres, tout est désactivé.

**Comment by flowbe** [comment]
Duplicate of #177
