### ISSUE TITLE
Déconnexion de mes deux comptes kDrive

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/ios-kDrive#185]
Je suis régulièrement déconnecté de mes deux comptes dans l'app, surtout lorsque je mets à jour l'app. J'utilise testflight avec la version beta.

**Comment by STXPH4NE** [comment]
Bonjour,
Depuis la dernière version, le bug qui était présent chez moi aussi, à l'air d'avoir disparu. Cela fait plusieurs jours que la connexion est maintenue apparemment !

**Comment by flowbe** [comment]
Merci pour ce retour, nous fermons donc cette issue
