### ISSUE TITLE
Séparateur journalier - upload de photo

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/ios-kDrive#188]
Lors du click sur le "+" pour upload une photo - mettre en place des séparateur par jour, comme sur la vue photo classique, pour une meilleure lisibilité.

![image](https://user-images.githubusercontent.com/84569752/124740033-ac6e8500-df1a-11eb-923b-cd3ad7d5bce9.png)

**Comment by alxschilling** [comment]
discuté en réunion. La vue affichée est une vue système donc modification non prévue.

**Comment by STXPH4NE** [comment]
Bonjour, dans ce cas comment expliquez-vous que les vues système soient différentes chez pCloud, qui pour le coup propose une vue avec des séparateurs journaliers ? Cf les photos ci-jointes. On peut d'ailleurs également voir que les vues de dossiers sont différentes, et pourtant clairement fournies par iOS dans les deux cas. Merci. (Désolé pour tous les gribouillages sur mes captures)
![IMG_6787](https://user-images.githubusercontent.com/86313398/124767513-2bbe8180-df38-11eb-93c3-ca5e8b51c00c.jpg)
![IMG_6786](https://user-images.githubusercontent.com/86313398/124767524-2cefae80-df38-11eb-8488-104729df354f.jpg)
![IMG_6785](https://user-images.githubusercontent.com/86313398/124767531-2d884500-df38-11eb-9666-12978e62a02d.jpg)
![IMG_6784](https://user-images.githubusercontent.com/86313398/124767533-2e20db80-df38-11eb-9a39-2b91b0feeaf5.jpg)

**Comment by flowbe** [comment]
Bonjour @STXPH4NE,
Le sélecteur de photos de pCloud n'est pas celui d'iOS, c'est une vue qu'ils ont codé manuellement. Nous avons opté pour la vue système pour les raisons suivantes :

- C'est une vue déjà familière aux utilisateurs car elle est déjà utilisée par de nombreuses autres applications, y compris celles d'Apple
- Elle est plus respectueuse de la vie privée car nous n'avons pas accès aux photos non sélectionnées, alors qu'une vue personnalisée nécessiterait de demander l'accès à toute la photothèque
- Elle offre des fonctionnalités qui seraient compliquées à implémenter manuellement comme la recherche

Nous espérons que vous comprendrez mieux notre choix avec ces informations
