### ISSUE TITLE
Download from the File app stuck

### ISSUE THREAD

**Issue by adrien-pedrina** [Infomaniak/ios-kDrive#241]
Hello,

On the latest version, 4.0.7 b3, the download via the iOS File app crashes and leaves the download running indefinitely.

No problem with the same files on the kDrive app, but it crashes on the Apple specific one.

See the video in PJ, possible to reproduce it without problem by trying 2x to download more than 2 files at the same time.

https://user-images.githubusercontent.com/85635056/128207903-4637140b-864e-45e7-873f-9a724f20b277.MP4

Will verify ASAP when 4.0.8 is available.

**Comment by adrien-pedrina** [comment]
Just tested with 4.0.8, same thing

**Comment by flowbe** [comment]
Version 4.0.9 build 6 tweaks a few things that may improve this. Feedback welcomed

**Comment by adrien-pedrina** [comment]
Unfortunately the problem is still there.

After a complete reboot of the iPad, as soon as you start editing files, the app seems to lose its connection and then the famous "pending" appears.

Latest TestFlight version installed, 4.0.9 (6) and iOS 15b6 

https://www.swisstransfer.com/d/a57cdde2-4fda-4d6a-b031-7356016b86c4

**Comment by flowbe** [comment]
As a workaround, when a download is stuck it seems that making a long press and tapping "Download" again unstuck it. I'll look at a real fix for this problem but this can help for now.
![image](https://user-images.githubusercontent.com/8288625/130576589-c5cb9329-1556-41f9-82fc-bcadb81de5e8.png)

**Comment by PhilippeWeidmann** [comment]
Could you please check if the latest beta resolves the issue ?

**Comment by PhilippeWeidmann** [comment]
Since there was no feedback we are closing this issue. Feel free to reopen it in case it's not working.
