### ISSUE TITLE
Soucis import PDF multiple

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/ios-kDrive#246]
Bonjour,

J’ai constaté qu’il y a un soucis lors de l’importation de fichiers depuis iOS vers kDrive.

J’ai voulu importer plusieurs fichiers PDF depuis une application vers kDrive.

En important le premier fichier kDrive m'envoie une notification me disant que « Importation terminée. 2 fichiers ont été importés. » alors que je n’en avais importé qu’un seul.

Je m’aperçois qu’un second fichier à probablement été crée lors de l’importation et qui se nomme « texte.txt » Ci-joint une capture d’écran de son contenu:

Le fichier PDF lui s’intitule par défaut undefined.pdf

Le problème est que si j’importe un second fichier pdf juste après, le nouveau fichier vient écraser undefined.pdf par le nouveau à moins que je ne prenne le temps de le renommer avant l’importation du second fichier pdf.

**Comment by alxschilling** [comment]
![image](https://user-images.githubusercontent.com/84569752/128669100-26c1bf88-b2b2-4ac6-9470-a9d52805b7c8.png)
![image](https://user-images.githubusercontent.com/84569752/128669117-25afe222-69d9-4855-b989-a0ff98363642.png)
![image](https://user-images.githubusercontent.com/84569752/128669133-18d26189-15e3-4b4d-a8e9-1219189e7745.png)

**Comment by PhilippeWeidmann** [comment]
Est-ce qu'il serait possible de connaitre l'application utilisée pour exporter le document en PDF et la marche à suivre pour reproduire le problème ?
Si deux fichiers sont importés, kDrive devrait normalement proposer des champs pour renommer les fichiers dans la vue d'importation.

**Comment by alxschilling** [comment]
je demande

**Comment by PhilippeWeidmann** [comment]
C'est la manière dont l'application tierce partage le/les document/s avec kDrive. On va vérifier si on a moyen de faire qqch à ce sujet.
