### ISSUE TITLE
Disconnection of accounts

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/ios-kDrive#248]
My infomaniak accounts are regularly disconnected from the kDrive app. This happened with the second last version recently deployed. This happens in the background when the app is not in use. I have two accounts connected to the app (a pro NEXT account and a normal Team account). My phone (iPhone 11 Pro) uses the latest version of iOS. I am at your disposal if you need more information.

Screenshot: https://www.swisstransfer.com/d/cf656285-302b-48db-8ef3-f7bd23c22a8c

**Comment by PhilippeWeidmann** [comment]
Did you use the latest beta on TestFlight (4.0.9 b3) ? We deployed a fix that should resolve the issue and we are closely monitoring any event regarding disconnection and we haven't receive any event for now.

**Comment by ik-tjacobse** [comment]
@PhilippeWeidmann Yes, I was using the beta on TestFlight. I did not experience any disconnection since the last update (4.0.9-3). Thanks for your follow-up.
