### ISSUE TITLE
Crash on Drop Box opening

### ISSUE THREAD

**Issue by marcheimendinger** [Infomaniak/ios-kDrive#293]
**Description**
The app crash while opening a Drop Box.

**Steps to reproduce**
1. Create a Drop Box.
2. Open it using the file explorer (second tab).
3. Enjoy the crash.

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - iOS version: 14.6
 - App version: 4.0.9 (6) TestFlight

**Additional context**
I sent a bug report using the iOS crash popup.

**Comment by flowbe** [comment]
Hi Marc,

Thank you for your feedback, we have your crash report and we will look into it. It would be very helpful if you had a video too.
We fixed several bugs related to the drop boxes in 4.0.9 beta 6 so it's weird that it's still happening.
