### ISSUE TITLE
Soucis de crash nouvelle version

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/ios-kDrive#336]

**Comment by alxschilling** [comment]
![image](https://user-images.githubusercontent.com/84569752/135578807-3371533d-18c2-47d3-9e98-db5b420c11a7.png)

**Comment by PhilippeWeidmann** [comment]
After investigation it looks like it's not related to VoiceOver but more generally to uploads. We are still trying to figure out why.

**Comment by PhilippeWeidmann** [comment]
A fix is available with the latest release (4.0.11) please reopen the issue if it's still happening.

**Comment by alxschilling** [comment]
Thanks !
