### ISSUE TITLE
Gestion des fichiers .url

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/ios-kDrive#367]
https://www.figma.com/proto/U67ckH2cNxQ5FHGckMsRfo/kDrive---Webview?node-id=262%3A2393&scaling=contain&page-id=1%3A2&starting-point-node-id=214%3A1144&show-proto-sidebar=1

**Comment by alxschilling** [comment]
Limitatie du scope à l'ouverture des fichiers

**Comment by PhilippeWeidmann** [comment]
Also handle importing FileImportHelper:115
