### ISSUE TITLE
Coupure lecture audio

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/ios-kDrive#368]
La vidéo montre le problème : https://100338.connect.drive.infomaniak.com/index.php/f/01761143

**Comment by PhilippeWeidmann** [comment]
I think it is related to #358 and a fix was released in the latest beta. Are you using the latest version ?

**Comment by flowbe** [comment]
@ik-tjacobse please install version 4.1.0 from TestFlight and try again

**Comment by ik-tjacobse** [comment]
I now only use the final version. I'll come back if this issue is not fixed when it will be release. Thank you for your follow-up.

**Comment by flowbe** [comment]
Should be fixed in [4.1.0](https://github.com/Infomaniak/ios-kDrive/releases/tag/4.1.0-Release). Feel free to create new issues for bugs in this version.
