### ISSUE TITLE
Changement de dossier après upload

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/ios-kDrive#372]
Après avoir envoyé 2 fichiers vidéos, je suis automatiquement redirigé à la racine du Drive.

Process:

1. Création d'un nouveau dossier
2. Envoi de deux vidéos
3. Le téléphone se met en veille automatiquement
4. Au déverrouillage du téléphone, je suis à la racine du Drive et je dois retourner dans le dossier manuellement si je souhaite voir les fichiers envoyés

Version 4.0.12

**Comment by PhilippeWeidmann** [comment]
I think it's also related to #358 . Please try with 4.1.0

**Comment by flowbe** [comment]
Should be fixed in [4.1.0](https://github.com/Infomaniak/ios-kDrive/releases/tag/4.1.0-Release). Feel free to create new issues for bugs in this version.
