### ISSUE TITLE
Feedback user - à vérifier

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/ios-kDrive#473]
Bonjour,

Je me permets de vous signaler qu'il est fréquent que des vidéos et autres fichiers ne veuillent pas se synchroniser sur kDrive depuis iOS. J'ai beau réessayer plusieurs fois, rien n'y fait et je n'y vois aucune logique à part le fait qu'il s'agit souvent de vidéos.

Par ailleurs, des vidéos/photos qui sont pourtant depuis un moment synchonisées sur kDrive ne se suppriment pas automatiquement avant plusieurs semaines alors que cette option est pourtant cochée.

Sinon, à l'exception de ces petits détails, je trouve votre système plutôt bon et j'apprécie vos interactions avec vos clients!

**Comment by flowbe** [comment]
- Concernant les fichiers qui ne se synchronisent pas, une amélioration du système a été faite et sera disponible en bêta aujourd'hui. Est-ce que les vidéos qui ne s'upload pas sont des ralentis ?
- Pour l'autre problème, nous allons investiguer. À savoir que la demande de suppression n'apparait que lorsqu'il n'y a plus d'autres uploads en cours

**Comment by PhilippeWeidmann** [comment]
Disponible dans la beta 4.1.2 (1)

**Comment by flowbe** [comment]
Pas trouvé de problème particulier avec la suppression automatique des photos

**Comment by PhilippeWeidmann** [comment]
No follow up. Reopen if needed.
