### ISSUE TITLE
Bug with multi selection

### ISSUE THREAD

**Issue by sirambd** [Infomaniak/ios-kDrive#481]
**Description**
When we activate the multi-selection from the `FileList`, and we navigate in the `bottomNavigation` to go for example to the reception, the selection remains active, which can lead to a lot of bug, because we can keep it active and change for example user

**Steps to reproduce**
1. Go to FileList
2. Enable multi selection
3. Change user
4. Go back to FileList

**Expected behavior**
Stop selection when bottom navigation has been changed

**Screenshots**
![image](https://user-images.githubusercontent.com/28200274/146753793-a5536eb5-dc42-41cd-96df-fec3f559ad6f.png)

**Smartphone**
 - Device: iPhone XR Infomaniak
 - iOS version: 15.1
 - App version: 4.1.1

**Comment by PhilippeWeidmann** [comment]
We have to disable multi selection upon leaving current file list
