### ISSUE TITLE
App ios (ipad uniquement) : choix du KDrive mais pas le choix du compte

### ISSUE THREAD

**Issue by cedricstocke** [Infomaniak/ios-kDrive#761]
si plusieurs comptes sont connectés à l'app KDrive et que je veux partager un fichier depuis l'explorateur de fichier intégré 
je n'ai pas le choix du compte (si le compte affiché a plusieurs KDrive j'ai le choix du KDrive mais je ne peux pas changer de compte) ([IMG_0028.png](https://trello.com/1/cards/62555279a5eba356c0fd756d/attachments/625552e0c10aac8177cf167a/download/IMG_0028.png) ) 

contrairement à l'app sur iphone ou je peux choisir le compte ( [IMG_0004 (1).png](https://trello.com/1/cards/62555279a5eba356c0fd756d/attachments/62555311ab5bcd31954ab699/download/IMG_0004_(1).png) )

(les 2 app sont a la même version, 4.2.0)

---

edit:

depuis l'app photo partager de la même façon me permet de choisir le compte que je veux

depuis l'explorateur de fichier selon l'option de partage que je choisi, j'ai deux fenêtre différentes ([IMG_0033.jpg](https://trello.com/1/cards/62555279a5eba356c0fd756d/attachments/62556303a0f52d08d1860807/download/IMG_0033.jpg) )
- avec l'option 1 en jaune je ne peux pas choisir
- avec l'option 2 en vert je peux choisir le compte

l'option 2 ouvre d'ailleurs un menu complètement différent et qui ne semble pas très adapté à la taille de l'écran ([IMG_0034.png](https://trello.com/1/cards/62555279a5eba356c0fd756d/attachments/62556367e2b71c40e56a9017/download/IMG_0034.png) )

**Comment by PhilippeWeidmann** [comment]
Couldn't reproduce account switch issue. 
Action sheet size has been increased with #782
