### ISSUE TITLE
Files not loading using Files.app

### ISSUE THREAD

**Issue by marcheimendinger** [Infomaniak/ios-kDrive#81]
Some files are not loading when trying to open them from the first-party Files.app. The usual loading spinner is animating infinitely.

These files correctly open when being inside the kDrive app.

I'm using kDrive `4.0.2` on iPadOS `14.5`.

**Comment by PhilippeWeidmann** [comment]
#79 and #84 should help with this issue.

Could you please test if the latest beta build (4.0.3 build 1) (available here https://testflight.apple.com/join/LLkIVadw) helps with your issue ?

**Comment by marcheimendinger** [comment]
The issue persists on some other files but the ones which had the issue can now be loaded. Since this new build I now have (at least one) greyed out file in Files.app which cannot be selected.

**Comment by adrien-pedrina** [comment]
Hello,

Same problem on iPad, some files are simply grayed out, even if the app is open at the same time.

Device : iPad Pro 11 2018
iOS : 14.6
kDrive : 4.0.4

https://www.swisstransfer.com/d/b2a4c258-bb96-4f3a-a609-b4649e004b5c

**Comment by flowbe** [comment]
Seems related to the type of file. Can you confirm that this happens on iWork files specifically (.numbers, .key and .pages)?

**Comment by adrien-pedrina** [comment]
Yes, i've just tested with the Keynote App, with a .key file, and it does the same :

(https://user-images.githubusercontent.com/85635056/122564008-2ced4480-d045-11eb-898c-5e2bc39cf33d.png)

**Comment by flowbe** [comment]
Awesome, thanks! We're looking into it.
