### ISSUE TITLE
Background import

### ISSUE THREAD

**Issue by GregLoichot** [Infomaniak/ios-kDrive#915]
**Description**
When importing a lot of files, if the user close the kDrive app or lock the iPhone, errors occur ("Erreur d'importation : impossible d'importer le fichier").

**Steps to reproduce**
1. Add a lot of files to your kDrive ; the import starts.
2. Leave the kDrive App or lock your phone.
3. Wait seconds until errors occur.

**Expected behavior**
When the app is in background, files in the queue should continue to be imported.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - iOS version: 16.1.1
 - App version: 4.2.5

**Misc**
Configuration on the phone: background activity enable for kDrive App.

**Comment by PhilippeWeidmann** [comment]
Hi,

Thank you for you detailed issue, we are aware of numerous issues with the background upload of a large number of files using kDrive. 
The team will focus early 2023, to improve the background upload functionality in the app.

**Comment by JorisBodin** [comment]
The upload on iOS will be completely revised from January 2023. This is going to be one of the very big future works for the application.
But we don't know yet how long it will take us to do this
We absolutely want to avoid doing tricks like Dropbox did by asking for example the access to geolocation to regularly activate the application in the background.

**Comment by adrien-coye** [comment]
Background mode is alright now, within what's possible with Apple APIs. Closing this one.
