### ISSUE TITLE
Disable video reencoding

### ISSUE THREAD

**Issue by GregLoichot** [Infomaniak/ios-kDrive#916]
It would be nice to have the option to disable the "reeconding" of video files (like for the photos heic vs jpg).

When uploading videos via the Apple Files app to kdrive, videos are kept in their original format (and size). When uploading videos via the kDrive app, videos are somehow reencoded losing quality.

So, could you add a toggle to enable video files without any modifications?

Thank you for supporting and developing the app. We really need swiss alternative to big tech solutions.

**Comment by PhilippeWeidmann** [comment]
Hi, 
When importing pictures from the "Plus" button we are using a flow which allows us to import the selected medias without asking for a permission, this allows the user to keep a high privacy setting for the photo library access (either Limited access or restricted).
However, with this method we get, as you said, a downgraded version of the media.

The team will discuss solutions to improve this behaviour, thank you for your comment.

-- Notes for the team --

We can retrieve PHAsset identifier when using the picker however the user has to explicitly allow library access.
We could check if we have a PHAssets identifier:
- If we have one, this means that we can access the original video file and upload it.
- If we don't have one, we fallback to the current method and upload the video provided by Apple.

If we do this, we should probably provide a warning to the user to inform him of the reduced video quality.

**Comment by PhilippeWeidmann** [comment]
Full libary access will also be required to import pictures / videos from the plus button.

If user denied the permission (limited | denied), present an alert to redirect to the settings.
