### ISSUE TITLE
Mark whole folder as available offline

### ISSUE THREAD

**Issue by marcheimendinger** [Infomaniak/ios-kDrive#94]
**Is your feature request related to a problem? Please describe.**
When I want to take a whole project with me, I have to mark each file in project folder as available offline and have to do it again if I add new files.

**Describe the solution you'd like**
Being able to mark a whole folder as available offline.

**Comment by alxschilling** [comment]
Hi Marc,

Many thanks for this, we discussed it with the team and we will put this task in the development backlog. 
We first need to stabilise the app and work on the critical topics and we will address all the enhancement tasks in a second wave.

With kind regards,

Alex
