### ISSUE TITLE
Photo sync setting 

### ISSUE THREAD

**Issue by alxschilling** [Infomaniak/ios-kDrive#97]
Customer reported an issue when the photo sync setting, which was set to ON, has automatically been turned to OFF and the photos stopped synchronising.
Investigation needed.

**Comment by flowbe** [comment]
We have been unable to reproduce this issue for now. If someone has a lead on how to reproduce, feel free to comment on this issue.

**Comment by flowbe** [comment]
It appears that the issue was still present even after this fix. We fixed it in #177
