### ISSUE TITLE
iPhone Storage says that kDrive app takes up >600 GB of space

### ISSUE THREAD

**Issue by Acranius** [Infomaniak/ios-kDrive#987]
**Description**

When going to Settings → General → iPhone Storage, iOS says that the kDrive app is taking up >600 GB of storage space.
While the value on top seems to be correct (_355.5 GB of 512 GB Used_),

- the red bar indicates that apps take up all the storage.

![iOS: Settings Storage](https://user-images.githubusercontent.com/2743065/233868718-1fcef74f-6554-4be4-8559-fcbef6a319e3.png)

- the kDrive entry says _654.6 GB_ which can't be true on a device with 512 GB capacity.

![iOS: Settings Storage - kDrive](https://user-images.githubusercontent.com/2743065/233868723-965ddcde-bb84-477a-9d55-b3184e47108e.png)

A similar value can be seen in the kDrive app when switching to the user tab on the bottom right, then going to _Settings_ and finally to _Manage local storage_.

![iOS: kDrive Settings - Manage local storage](https://user-images.githubusercontent.com/2743065/233869134-d78221b3-8d46-4eea-8c3c-5be77e467b2a.png)

However, the two values don't match exactly.

**Steps to reproduce**

I stumbled on the issue while checking the available storage on my iPhone.

I haven't installed the kDrive on another iPhone, so I can't verify it the issue is on every device.
To check the values, follow the steps in the description.

**Expected behavior**

iOS should state the correct value in the settings.

**Smartphone**

 - Device: iPhone 12 Pro Max
 - iOS version: iOS 16.4.1
 - App version: 4.3.0

**Additional context**

When tapping on any item in the _Data_ list in _Manage local storage_, the modal window's title says _Clear cache_.
I'm afraid to confirm to clear it, especially for the _Imports_ data.

What does confirming this modal do exactly?

![iOS: kDrive Settings - Manage local storage (Clear cache Imports)](https://user-images.githubusercontent.com/2743065/233869366-d6d0129a-c995-4e4c-a6ef-cc5218f71f8c.png)

**Comment by Acranius** [comment]
When investigating further and checking my storage on the web app, I saw that the file versions take up most of the space.
This is not visible in the iOS app currently.

![kDrive: Web Storage](https://user-images.githubusercontent.com/2743065/233871070-a25886f0-a4cb-405e-9a64-466373f906b1.png)

Most of them are photos and videos coming from the photo backup and have never been edited, which means they are identical.

![kkDrive: Web Storage - File](https://user-images.githubusercontent.com/2743065/233871089-a6ff3979-71cf-4688-a8e8-b19bf4f71a8b.png)

Some of them have >20 versions, which definitely adds to the storage used.

![kDrive: Web Storage - File Delete](https://user-images.githubusercontent.com/2743065/233871194-cfccc0fa-b508-43d2-bd12-b0470187063f.png)

Deleting old versions to free up space can't be done automatically currently.
Maybe add an option to disable versioning for specific folders?

**Comment by PhilippeWeidmann** [comment]
Hi thank you for your detailed issue.

We will investigate on our side.

Have you tried to upload multiple times your photo library or is this the result of only one attempt ?

For now as a simple workaround: if you do not have any import in progress you can safely delete the "Import" section by clicking on it.

**Comment by PhilippeWeidmann** [comment]
Decrementing the date value step by step will trigger a complete reupload even for the existing pictures. As said in #988 this is not a desired behaviour and will be fixed.

Regarding the iCloud backup, you can remove kDrive but this will could lead to the following issues in case you restore from the backup:
- You might need to log back in the app. (I'm not a 100% sure about this as login credentials are stored in the Keychain)
- You will lose the status for the files marked as "available offline" (white checkmark over green background ✅), the file is saved in the cloud on your kDrive, only the status will be lost).
- All the cached files will need to be downloaded again and won't be available offline (this process is transparent for the user)

Either way, we can do better and we need to mark only some directories as available for iCloud backup.

**Comment by Acranius** [comment]
> You might need to log back in the app. (I'm not a 100% sure about this as login credentials are stored in the Keychain)

Not an issue imo, since restoring from a backup is not a common scenario and logging back in to an app is not a hindrance for users, especially if the app is one that protects your data.

>You will lose the status for the files marked as "available offline" (white checkmark over green background ✅), the file is saved in the cloud on your kDrive, only the status will be lost).

I don't have any offline files, so this does not affect me. However, I don't think that's a big issue either.

>All the cached files will need to be downloaded again and won't be available offline (this process is transparent for the user)

It's not clear to me what files are cached. I couldn't find any information about the different types of data on the help page.

Also, it doesn't matter which type of data you intend to delete in "Manage local storage", the prompt title is always _"Clear cache"_.

| Type of data | Usage |
|--------|--------|
| Drives & offline files | clear |
| Other documents | not clear |
| File Provider Storage | not clear |
| Imports | not clear <br> took ~600 GB of my local storage according to the app |
| Temporary files | not clear <br> takes a lot of storage too | 
| Cache | not clear | 

Could you add the missing information to the help page?

## iCloud backup size

After deleting all the caches in the kDrive app, the iCloud backup size is now < 100 KB.

![iOS Settings: Backup Details - kDrive](https://user-images.githubusercontent.com/2743065/235365329-4b92d055-f295-4963-824a-5891cce72245.png)

The storage issue can be resolved when deleting data manually, but the iCloud backup should not include cached files.

**Comment by PhilippeWeidmann** [comment]
The alert always displays "Clear cache" but the secondary text should have a description matching the category you are trying to clean

**Comment by PhilippeWeidmann** [comment]
Internal note to resolve the issue:
Use https://developer.apple.com/documentation/foundation/urlresourcevalues/1780002-isexcludedfrombackup to exclude cached realm from iCloud backup

**Comment by adrien-coye** [comment]
WIP: https://github.com/Infomaniak/ios-kDrive/pull/994

**Comment by PhilippeWeidmann** [comment]
This should be resolved by now. Feel free to reopen the issue if your problem is still occuring.
